### ISSUE TITLE
loadFromAsset or load?

### ISSUE THREAD

**Issue by ahmad88me** [tejainece/flutter_sprite#3]
I tested the example locally it works perfectly. However, when I try to load it locally, I get the following error: `Error: Member not found: 'Sprite.loadFromAsset'.`  I am using the latest version: which is `flutter_sprite: ^3.0.5` with MacOS.

But when I use the `load` I got the following error:
```
 Exception: sprites is mandatory
#0      SpriteSheetSpec.fromJson (package:flutter_sprite/src/model/format.dart:113:7)
#1      Sprite.load (package:flutter_sprite/src/model/sprite.dart:44:34)
```

**Comment by ahmad88me** [comment]
The found the problem. Seems like the latest version here is different. I solve the problem by adding the following in the dependencies:
```
  flutter_sprite:
   git:
    url: https://github.com/tejainece/flutter_sprite.git
``` 

and now it works
